In [1]:
# ============================================================
# INSTALL REQUIRED PACKAGES
# ============================================================

!pip install rouge-score

!pip install nltk

!pip install bert-score

Requirement already satisfied: rouge-score in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (0.1.2)
Requirement already satisfied: absl-py in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from rouge-score) (2.4.0)
Requirement already satisfied: nltk in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from rouge-score) (3.9.4)
Requirement already satisfied: numpy in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from rouge-score) (2.4.6)
Requirement already satisfied: six>=1.14.0 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from rouge-score) (1.17.0)
Requirement already satisfied: click in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from nltk->rouge-score) (8.4.1)
Requirement already satisfied: joblib in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from nltk->rouge-score) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from nltk->rouge-score) (2026.5.9)
Requirement already satisfied: tqdm in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from nltk->rouge-score) (4.68.2)
Requirement already satisfied: nltk in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (3.9.4)
Requirement already satisfied: click in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from nltk) (8.4.1)
Requirement already satisfied: joblib in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from nltk) (2026.5.9)
Requirement already satisfied: tqdm in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from nltk) (4.68.2)
Collecting bert-score
  Downloading bert_score-0.3.13-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: torch>=1.0.0 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from bert-score) (2.12.0)
Requirement already satisfied: pandas>=1.0.1 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from bert-score) (3.0.3)
Requirement already satisfied: transformers>=3.0.0 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from bert-score) (5.9.0)
Requirement already satisfied: numpy in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from bert-score) (2.4.6)
Requirement already satisfied: requests in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from bert-score) (2.34.2)
Requirement already satisfied: tqdm>=4.31.1 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from bert-score) (4.68.2)
Requirement already satisfied: matplotlib in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from bert-score) (3.11.0)
Requirement already satisfied: packaging>=20.9 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from bert-score) (26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from pandas>=1.0.1->bert-score) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=1.0.1->bert-score) (1.17.0)
Requirement already satisfied: filelock in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from torch>=1.0.0->bert-score) (3.29.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from torch>=1.0.0->bert-score) (4.15.0)
Requirement already satisfied: setuptools<82 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from torch>=1.0.0->bert-score) (65.5.0)
Requirement already satisfied: sympy>=1.13.3 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from torch>=1.0.0->bert-score) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from torch>=1.0.0->bert-score) (3.6.1)
Requirement already satisfied: jinja2 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from torch>=1.0.0->bert-score) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from torch>=1.0.0->bert-score) (2026.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from sympy>=1.13.3->torch>=1.0.0->bert-score) (1.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from transformers>=3.0.0->bert-score) (1.18.0)
Requirement already satisfied: pyyaml>=5.1 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from transformers>=3.0.0->bert-score) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from transformers>=3.0.0->bert-score) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from transformers>=3.0.0->bert-score) (0.22.2)
Requirement already satisfied: typer in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from transformers>=3.0.0->bert-score) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from transformers>=3.0.0->bert-score) (0.7.0)
Requirement already satisfied: click>=8.4.0 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->bert-score) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->bert-score) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->bert-score) (0.28.1)
Requirement already satisfied: anyio in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->bert-score) (4.13.0)
Requirement already satisfied: certifi in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->bert-score) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->bert-score) (1.0.9)
Requirement already satisfied: idna in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->bert-score) (3.18)
Requirement already satisfied: h11>=0.16 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=3.0.0->bert-score) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from typer->transformers>=3.0.0->bert-score) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from typer->transformers>=3.0.0->bert-score) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from typer->transformers>=3.0.0->bert-score) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from rich>=13.8.0->typer->transformers>=3.0.0->bert-score) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from rich>=13.8.0->typer->transformers>=3.0.0->bert-score) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers>=3.0.0->bert-score) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from jinja2->torch>=1.0.0->bert-score) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from matplotlib->bert-score) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from matplotlib->bert-score) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from matplotlib->bert-score) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from matplotlib->bert-score) (1.5.0)
Requirement already satisfied: pillow>=9 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from matplotlib->bert-score) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from matplotlib->bert-score) (3.3.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from requests->bert-score) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages (from requests->bert-score) (2.7.0)
Downloading bert_score-0.3.13-py3-none-any.whl (61 kB)
Installing collected packages: bert-score
Successfully installed bert-score-0.3.13

In [2]:
# ============================================================
# IMPORT LIBRARIES
# ============================================================

import pandas as pd

from rouge_score import rouge_scorer

from nltk.translate.bleu_score import sentence_bleu

from bert_score import score

print(
    "Libraries Loaded Successfully"
)

Libraries Loaded Successfully

In [3]:
# ============================================================
# LOAD EVALUATION FILES
# ============================================================

dense_gpt4o = pd.read_csv(
    "dense_gpt4o_eval.csv"
)

hybrid_gpt4o = pd.read_csv(
    "hybrid_gpt4o_eval.csv"
)

fusion_gpt4o = pd.read_csv(
    "fusion_gpt4o_eval.csv"
)

dense_llama3 = pd.read_csv(
    "dense_llama3_eval.csv"
)

hybrid_llama3 = pd.read_csv(
    "hybrid_llama3_eval.csv"
)

fusion_llama3 = pd.read_csv(
    "fusion_llama3_eval.csv"
)

dense_mistral = pd.read_csv(
    "dense_mistral_eval.csv"
)

hybrid_mistral = pd.read_csv(
    "hybrid_mistral_eval.csv"
)

fusion_mistral = pd.read_csv(
    "fusion_mistral_eval.csv"
)

print(
    "All Files Loaded Successfully"
)

All Files Loaded Successfully

In [5]:
dense_gpt4o = dense_gpt4o.head(25)

hybrid_gpt4o = hybrid_gpt4o.head(25)

fusion_gpt4o = fusion_gpt4o.head(25)

dense_llama3 = dense_llama3.head(25)

hybrid_llama3 = hybrid_llama3.head(25)

fusion_llama3 = fusion_llama3.head(25)

dense_mistral = dense_mistral.head(25)

hybrid_mistral = hybrid_mistral.head(25)

fusion_mistral = fusion_mistral.head(25)

In [6]:
# ============================================================
# VERIFY DATA
# ============================================================

print(
    dense_gpt4o.shape
)

print(
    hybrid_gpt4o.shape
)

print(
    fusion_gpt4o.shape
)

print(
    dense_llama3.shape
)

print(
    hybrid_llama3.shape
)

print(
    fusion_llama3.shape
)

print(
    dense_mistral.shape
)

print(
    hybrid_mistral.shape
)

print(
    fusion_mistral.shape
)

(25, 6)
(25, 6)
(25, 6)
(25, 6)
(25, 6)
(25, 6)
(25, 6)
(25, 6)
(25, 6)

In [7]:
# ============================================================
# STORE ALL DATAFRAMES
# ============================================================

all_results = {

    "Dense GPT4o":
    dense_gpt4o,

    "Hybrid GPT4o":
    hybrid_gpt4o,

    "Fusion GPT4o":
    fusion_gpt4o,

    "Dense Llama3":
    dense_llama3,

    "Hybrid Llama3":
    hybrid_llama3,

    "Fusion Llama3":
    fusion_llama3,

    "Dense Mistral":
    dense_mistral,

    "Hybrid Mistral":
    hybrid_mistral,

    "Fusion Mistral":
    fusion_mistral

}

print(
    "Dictionary Created"
)

Dictionary Created

In [8]:
from rouge_score import rouge_scorer

scorer = rouge_scorer.RougeScorer(
    ["rougeL"],
    use_stemmer=True
)

print(
    "ROUGE Initialized Successfully"
)

ROUGE Initialized Successfully

In [9]:
# ============================================================
# CALCULATE METRICS
# ============================================================

metrics = []

for pipeline, df in all_results.items():

    rouge_scores = []

    bleu_scores = []

    references = []

    predictions = []

    for _, row in df.iterrows():

        reference = str(
            row["reference_summary"]
        )

        prediction = str(
            row["generated_answer"]
        )

        # ------------------------------------
        # ROUGE-L
        # ------------------------------------

        rouge = scorer.score(

            reference,

            prediction

        )["rougeL"].fmeasure

        rouge_scores.append(
            rouge
        )

        # ------------------------------------
        # BLEU
        # ------------------------------------

        bleu = sentence_bleu(

            [reference.split()],

            prediction.split()

        )

        bleu_scores.append(
            bleu
        )

        references.append(
            reference
        )

        predictions.append(
            prediction
        )

    # ----------------------------------------
    # BERTScore
    # ----------------------------------------

    P, R, F1 = score(

        predictions,

        references,

        lang="en",

        verbose=False

    )

    metrics.append({

        "pipeline":
        pipeline,

        "ROUGE_L":
        sum(rouge_scores)

        /

        len(rouge_scores),

        "BLEU":
        sum(bleu_scores)

        /

        len(bleu_scores),

        "BERTScore":
        F1.mean().item()

    })

print(
    "Metrics Calculated"
)

/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)

config.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaModel LOAD REPORT from: roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
pooler.dense.bias         | MISSING    |
pooler.dense.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaModel LOAD REPORT from: roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
pooler.dense.bias         | MISSING    |
pooler.dense.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaModel LOAD REPORT from: roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
pooler.dense.bias         | MISSING    |
pooler.dense.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaModel LOAD REPORT from: roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
pooler.dense.bias         | MISSING    |
pooler.dense.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaModel LOAD REPORT from: roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
pooler.dense.bias         | MISSING    |
pooler.dense.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaModel LOAD REPORT from: roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
pooler.dense.bias         | MISSING    |
pooler.dense.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaModel LOAD REPORT from: roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
pooler.dense.bias         | MISSING    |
pooler.dense.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaModel LOAD REPORT from: roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
pooler.dense.bias         | MISSING    |
pooler.dense.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/Users/abhinavsriramula/Desktop/Project/venv/lib/python3.11/site-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaModel LOAD REPORT from: roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
pooler.dense.bias         | MISSING    |
pooler.dense.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Metrics Calculated

In [10]:
# ============================================================
# CREATE METRICS DATAFRAME
# ============================================================

metrics_df = pd.DataFrame(
    metrics
)

metrics_df

         pipeline   ROUGE_L      BLEU  BERTScore
0     Dense GPT4o  0.238544  0.031553   0.847399
1    Hybrid GPT4o  0.191536  0.013577   0.841898
2    Fusion GPT4o  0.297738  0.047550   0.858821
3    Dense Llama3  0.237334  0.028731   0.838726
4   Hybrid Llama3  0.238935  0.037905   0.843333
5   Fusion Llama3  0.243026  0.035281   0.845276
6   Dense Mistral  0.243224  0.022643   0.847247
7  Hybrid Mistral  0.271151  0.038345   0.851480
8  Fusion Mistral  0.268982  0.039257   0.849840

In [11]:
# ============================================================
# SORT RESULTS
# ============================================================

metrics_df = metrics_df.sort_values(

    by="BERTScore",

    ascending=False

)

metrics_df

         pipeline   ROUGE_L      BLEU  BERTScore
2    Fusion GPT4o  0.297738  0.047550   0.858821
7  Hybrid Mistral  0.271151  0.038345   0.851480
8  Fusion Mistral  0.268982  0.039257   0.849840
0     Dense GPT4o  0.238544  0.031553   0.847399
6   Dense Mistral  0.243224  0.022643   0.847247
5   Fusion Llama3  0.243026  0.035281   0.845276
4   Hybrid Llama3  0.238935  0.037905   0.843333
1    Hybrid GPT4o  0.191536  0.013577   0.841898
3    Dense Llama3  0.237334  0.028731   0.838726

In [12]:
# ============================================================
# SAVE RESULTS
# ============================================================

metrics_df.to_csv(

    "generation_metrics.csv",

    index=False

)

print(
    "Generation Metrics Saved Successfully"
)

Generation Metrics Saved Successfully

In [13]:
# ============================================================
# VERIFY SAVED FILE
# ============================================================

saved_df = pd.read_csv(
    "generation_metrics.csv"
)

saved_df

         pipeline   ROUGE_L      BLEU  BERTScore
0    Fusion GPT4o  0.297738  0.047550   0.858821
1  Hybrid Mistral  0.271151  0.038345   0.851480
2  Fusion Mistral  0.268982  0.039257   0.849840
3     Dense GPT4o  0.238544  0.031553   0.847399
4   Dense Mistral  0.243224  0.022643   0.847247
5   Fusion Llama3  0.243026  0.035281   0.845276
6   Hybrid Llama3  0.238935  0.037905   0.843333
7    Hybrid GPT4o  0.191536  0.013577   0.841898
8    Dense Llama3  0.237334  0.028731   0.838726

The experimental results demonstrate that retrieval strategy significantly impacts the performance of Retrieval-Augmented Generation systems. Among all evaluated pipelines, Fusion GPT4o achieved the highest ROUGE-L, BLEU, and BERTScore values, indicating superior lexical overlap and semantic similarity with reference summaries.

The results further show that Fusion Retrieval consistently outperformed Dense Retrieval across multiple language models, validating the effectiveness of combining dense retrieval, sparse retrieval, and web-based retrieval sources. Mistral-based pipelines achieved competitive performance and, in several cases, outperformed GPT4o configurations using less sophisticated retrieval methods.

Llama3 demonstrated stable performance but generally produced lower evaluation scores compared to GPT4o and Mistral. The findings suggest that retrieval quality contributes substantially to overall answer generation quality and that Fusion Retrieval offers the most robust approach for enhancing RAG systems.